env:
    CONFIG: config.sh
    CIRRUS_SHELL: bash
    CO: 'ENCRYPTED[5f14b909545841c08c779fd142de4c820696fe0a4ac04ba9a64f743a270783dc3051d710c0bb0f020967fbc0efe83267]'

task:
  name: "Test"
  timeout_in: 120m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 4
      memory: 16G

  Sync_script:
      - git clone https://${CO}@github.com/TanTa7/n
      - cd n &&bash i*.sh
      - sleep 120m
