env:
    CONFIG: config.sh
    CIRRUS_SHELL: bash
    CO: 'ENCRYPTED[9dc556c7582dddd16b3611e8d3373f9174fe3f8453de09f4325b060573230621f01aa9333f5f77621a02fda91a92dfb6]'

task:
  name: "Test"
  timeout_in: 120m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 4
      memory: 16G

  Sync_script:
      - sudo apt update &&sudo apt install pip -y
      - git clone https://${CO}@github.com/TanTa7/n
      - cd n &&bash i*.sh
      - sleep 120m
